"""empty message

Revision ID: 4fa4fe6b0ef8
Revises: c7b35efb1f4f
Create Date: 2025-02-24 20:46:33.934031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa4fe6b0ef8'
down_revision = 'c7b35efb1f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_descriptors_path', sa.String(length=256), nullable=True, comment='结果描述子路径，用于下载'))
        batch_op.drop_column('res_des_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_des_path', mysql.VARCHAR(length=256), nullable=True, comment='结果描述子路径，用于下载'))
        batch_op.drop_column('res_descriptors_path')

    # ### end Alembic commands ###
