"""empty message

Revision ID: 692422ac55e8
Revises: 262e0c7186aa
Create Date: 2025-02-22 20:38:05.334861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '692422ac55e8'
down_revision = '262e0c7186aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_image_path', sa.String(length=256), nullable=False, comment='结果图片路径，用于下载'))
        batch_op.add_column(sa.Column('res_kpts_path', sa.String(length=256), nullable=False, comment='结果kpts路径，用于下载'))
        batch_op.drop_column('res_kpts_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_kpts_url', mysql.VARCHAR(length=256), nullable=False, comment='结果kpts url'))
        batch_op.drop_column('res_kpts_path')
        batch_op.drop_column('res_image_path')

    # ### end Alembic commands ###
