"""empty message

Revision ID: 6ba840a2ae47
Revises: f4e5307b459a
Create Date: 2025-02-23 15:22:44.311140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ba840a2ae47'
down_revision = 'f4e5307b459a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_image_path', sa.String(length=256), nullable=False, comment='原图片Path'))
        batch_op.alter_column('origin_image_url',
               existing_type=mysql.VARCHAR(length=256),
               comment='原图片url，用于显示',
               existing_comment='原图片url',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.alter_column('origin_image_url',
               existing_type=mysql.VARCHAR(length=256),
               comment='原图片url',
               existing_comment='原图片url，用于显示',
               existing_nullable=False)
        batch_op.drop_column('origin_image_path')

    # ### end Alembic commands ###
