"""empty message

Revision ID: 746e29cad229
Revises: 
Create Date: 2025-02-22 16:04:34.902710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746e29cad229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('role', sa.String(length=64), nullable=False, comment='角色'),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱地址'),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_t_user_username'), ['username'], unique=True)

    op.create_table('t_detection',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('origin_image_name', sa.String(length=128), nullable=False, comment='原图片名（无uuid）'),
    sa.Column('origin_image_url', sa.String(length=256), nullable=False, comment='原图片url'),
    sa.Column('algorithm', sa.String(length=64), nullable=False, comment='使用算法'),
    sa.Column('config', sa.String(length=256), nullable=False, comment='参数'),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('elapsed_time', sa.Float(), nullable=False),
    sa.Column('res_image_url', sa.String(length=256), nullable=False, comment='结果图片url'),
    sa.Column('res_kpts_num', sa.Integer(), nullable=False, comment='kpts数量'),
    sa.Column('res_kpts_url', sa.String(length=256), nullable=False, comment='结果kpts url'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_detection')
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_user_username'))
        batch_op.drop_index(batch_op.f('ix_t_user_email'))

    op.drop_table('t_user')
    # ### end Alembic commands ###
