"""empty message

Revision ID: c7b35efb1f4f
Revises: 6ba840a2ae47
Create Date: 2025-02-24 20:21:34.658439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b35efb1f4f'
down_revision = '6ba840a2ae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_scores_path', sa.String(length=256), nullable=True, comment='结果分数路径，用于下载'))
        batch_op.add_column(sa.Column('res_des_path', sa.String(length=256), nullable=True, comment='结果描述子路径，用于下载'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.drop_column('res_des_path')
        batch_op.drop_column('res_scores_path')

    # ### end Alembic commands ###
