"""empty message

Revision ID: f4e5307b459a
Revises: 692422ac55e8
Create Date: 2025-02-22 20:44:02.473396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e5307b459a'
down_revision = '692422ac55e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_date', sa.DateTime(), nullable=False, comment='产生记录的时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_detection', schema=None) as batch_op:
        batch_op.drop_column('record_date')

    # ### end Alembic commands ###
